##
## EPITECH PROJECT, 2020
## OOP_arcade_2019
## File description:
## Makefile for the project
##

all:
	$(MAKE) -C ./nibbler/

debug:
	$(MAKE) -C ./nibbler/ debug

clean:
	$(MAKE) -C ./nibbler/ clean

fclean:
	$(MAKE) -C ./nibbler/ fclean

re:	fclean all

.PHONY:	all clean fclean re debug
