##
## EPITECH PROJECT, 2020
## OOP_arcade_2019
## File description:
## Makefile for the project
##

all:
	$(MAKE) -C ./sfml/

debug:
	$(MAKE) -C ./sfml/ debug

clean:
	$(MAKE) -C ./sfml/ clean

fclean:
	$(MAKE) -C ./sfml/ fclean

re:	fclean all

.PHONY:	all clean fclean re debug
